pod 'MJExtension'
pod 'AFNetworking'
pod 'OcticonsIOS'
pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell'
pod 'DateTools'
pod 'SDWebImage'
pod 'ChameleonFramework'
pod 'YTKKeyValueStore'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
